// <auto-generated />
using System;
using HTMLAnalysis.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HTMLAnalysis.Migrations
{
    [DbContext(typeof(WebFrequenciesDbContext))]
    [Migration("20180909190017_Url_Columns_RenamedTo_Source")]
    partial class Url_Columns_RenamedTo_Source
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HTMLAnalysis.Domain.Fetches.FetchEntity", b =>
                {
                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Source");

                    b.ToTable("Fetches");
                });

            modelBuilder.Entity("HTMLAnalysis.Domain.Frequencies.FrequencyEntity", b =>
                {
                    b.Property<string>("SaltedHash")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<string>("EncryptedWord")
                        .IsRequired();

                    b.Property<string>("FetchSource");

                    b.HasKey("SaltedHash");

                    b.HasIndex("FetchSource");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("HTMLAnalysis.Domain.Frequencies.FrequencyEntity", b =>
                {
                    b.HasOne("HTMLAnalysis.Domain.Fetches.FetchEntity", "Fetch")
                        .WithMany("Frequencies")
                        .HasForeignKey("FetchSource");
                });
#pragma warning restore 612, 618
        }
    }
}
